[init] 문서&폴더&프로젝트 Entity 최초 작성
sparta-team6/CO-UP-TEAM-BE pull request #57
Opened 2022-05-09 12:34 UTC by funnykyeon

2022-05-09 12:43 UTC, Hong-Seungmin requested changes

2022-05-09 12:43 UTC, Hong-Seungmin commented on src/main/java/hanghae/api/coupteambe/domain/entity/document/Document.java
> +@EntityListeners(AuditingEntityListener.class)
EntityListeners는 특정 동작을 감지해서 자동으로 처리해주는 Entity라고 생각하면됩니다.
[참고사이트](https://velog.io/@seongwon97/Spring-Boot-Entity-Listener)

Entity로 어노테이션 수정해야할 듯 합니다.

2022-05-09 12:43 UTC, Hong-Seungmin commented on src/main/java/hanghae/api/coupteambe/domain/entity/document/Document.java
> +    private Project pjId;
재호님과 동일한 이슈로, "JPA 연관관계" 검색바랍니다.

2022-05-09 12:43 UTC, Hong-Seungmin commented on src/main/java/hanghae/api/coupteambe/domain/entity/document/Document.java
> +    private MStatus mStatus = MStatus.M_STATUS_SUCCESS;
연관된 클래스는 함께 커밋바랍니다. (다른사람은 해당 클래스를 구할 수 없습니다)

2022-05-10 00:09 UTC, closed without merging

2022-05-10 00:56 UTC, pg-Parunson commented on src/main/java/hanghae/api/coupteambe/domain/entity/document/Document.java
> +    private MStatus mStatus = MStatus.M_STATUS_SUCCESS;
위에 보시면 MStatus 클래스는 "[init] MStatus 최초 작성"에 포함되어 커밋 되어있습니다. 😀